# Generated by Django 5.2.6 on 2025-09-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('dados_json', models.JSONField(help_text='Armazena os dados brutos do aluno do arquivo JSON')),
            ],
        ),
        migrations.CreateModel(
            name='PredicaoEvasao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risco_evasao', models.BooleanField(default=False)),
                ('probabilidade', models.FloatField(help_text='Probabilidade de evasão (ex: 0.75 para 75%)')),
                ('data_predicao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predicao', to='predicao.aluno')),
            ],
        ),
    ]
